package com.appointmentsystem.ai;

import com.appointmentsystem.model.Product;
import java.util.List;

/**
 * Represents the response generated by the Chatbot.
 * 
 * @author Elham
 * @version 1.0
 */
public class ChatResponse {

    /** The text message generated by the bot to respond to the user's query. */
    private String responseText;

    /** The list of recommended products retrieved by the RAG search engine. */
    private List<Product> recommendedProducts;

    /**
     * Constructs a new ChatResponse with a message and a list of products.
     *
     * @param responseText       the text message from the bot
     * @param recommendedProducts the list of recommended products
     */
    public ChatResponse(String responseText, List<Product> recommendedProducts) {
        this.responseText = responseText;
        this.recommendedProducts = recommendedProducts;
    }

    /**
     * Gets the text message of the response.
     *
     * @return the response text
     */
    public String getResponseText() {
        return responseText;
    }

    /**
     * Sets the text message of the response.
     *
     * @param responseText the new response text
     */
    public void setResponseText(String responseText) {
        this.responseText = responseText;
    }

    /**
     * Gets the list of recommended products.
     *
     * @return the list of recommended products
     */
    public List<Product> getRecommendedProducts() {
        return recommendedProducts;
    }

    /**
     * Sets the list of recommended products.
     *
     * @param recommendedProducts the new list of recommended products
     */
    public void setRecommendedProducts(List<Product> recommendedProducts) {
        this.recommendedProducts = recommendedProducts;
    }
}